### ISSUE TITLE
code crashes after four plays

### ISSUE THREAD

**Issue by djecken** [gallaugher/CPXBluefruitHalloweenHead#1]
Howdy! Really nice work on this :-) I'm adapting this for my pumpkin project (minus the cap touch piece). 

I noticed the program "crashes" after triggering four sounds. It doesn't seem to matter which ones are triggered and seems to be pretty consistent. Do you happen to have similar experience?

I tweaked the playwav function a bit. I mostly ripped it from my previous circuit python project with wave files. This allows you to place all of the audio files into a sound directly. Somehow, this fixes the issue above. I'm not sure why, but I thought I'd let you know. :-)

`def play_wav(name, loop=False):
    """
    Play a WAV file in the 'sounds' directory.
    :param name: partial file name string, complete name will be built around
                 this, e.g. passing 'foo' will play file 'sounds/foo.wav'.
    :param loop: if True, sound will repeat indefinitely (until interrupted
                 by another sound).
    """
    global wave_file  # pylint: disable=global-statement
    print("playing", name)
    if wave_file:
        wave_file.close()
    try:
        wave_file = open('sounds/' + name + '.wav', 'rb') # using wave files from sounds folder
        wave = WaveFile(wave_file)
        audio.play(wave, loop=loop)
    except OSError:
        pass # we'll just skip playing then`

The other thing I had to do was to add some time.sleep(xx) right after the calls to play_wav in the if statements so the RGB colors would stay on while the audio plays – this in turn requires specific timing for each wave file. 

Thanks again for sharing your work!

**Comment by gallaugher** [comment]
Thanks so much, Noe! I should have clarified in this. LadyAda & Jeff Epler fixed this issue in a version of the CircuitPython .uf2 that isn't officially released, but Lady Ada kindly linked it in the follow up reply you can find here: https://github.com/adafruit/circuitpython/issues/2203#issuecomment-541350225

The error occurs with 5.0 alpha 4. The english language US version of the .uf2 that solves this problem & that can be downloaded from above, is named: "adafruit-circuitpython-circuitplayground_bluefruit-en_US-20191012-a146ce5.uf2". LadyAda might be able to provide insight on when the next release will be offered. I've been using the new .uf2 pretty regularly & it seems to solve all of these problems.

I'm just delighted you've found the work interesting. Thanks for all of YOUR work. If you're ever in Boston, you have a standing invitation for a beverage of your choice :)

**Comment by djecken** [comment]
Ah that makes sense, thanks for the clarification! I'll grab the update and try that. If I'm ever in Boston, i'll keep you in mind. Thanks again, John :-)
